### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by aaronw2** [particle-iot/particle-dev#238]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: "openSUSE Leap
**Thrown From**: [particle-dev](https://github.com/particle-iot/particle-dev) package 0.2.2

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.processDirIncludes (/packages/particle-dev/lib/main.js:418:18)
    at /packages/particle-dev/lib/main.js:787:19
    at Object.minBuildTargetRequired (/packages/particle-dev/lib/main.js:347:10)
    at /packages/particle-dev/lib/main.js:744:16
    at Object.loginRequired (/packages/particle-dev/lib/main.js:296:10)
    at Object.compileCloud (/packages/particle-dev/lib/main.js:743:15)
    at /packages/particle-dev/lib/main.js:1195:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /packages/particle-dev/lib/main.js:969:25
    at /packages/particle-dev/lib/main.js:318:11
    at Object.loginRequired (/packages/particle-dev/lib/main.js:296:10)
    at Object.deviceRequired (/packages/particle-dev/lib/main.js:301:15)
    at Object.flashCloud (/packages/particle-dev/lib/main.js:927:15)
    at /packages/particle-dev/lib/main.js:1175:57)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:37 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:37 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -3:35.1.0 particle-dev:core-status-updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:53.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:40.2.0 particle-dev:core-status-updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:38 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -2:10.4.0 particle-dev:core-status-updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:59.1.0 console:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:55.3.0 particle-dev:show-serial-monitor (atom-pane.pane.active)
     -0:53.5.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:53.5.0 particle-dev:update-login-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:53.5.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:53.5.0 particle-dev:update-login-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:40.2.0 particle-dev:core-status-updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:18.7.0 particle-dev:flash-cloud (input.hidden-input)
     -0:09.7.0 particle-dev:core-status-updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-eclipse-syntax 0.0.5 
console-panel 0.3.0 
Hydrogen 2.2.2 
language-particle 0.3.5 
particle-dev 0.2.2 
particle-dev-cloud-functions 0.2.0 
particle-dev-cloud-variables 0.2.0 
particle-dev-complete 1.0.2 
particle-dev-exception-reporting 0.36.1 
particle-dev-libraries 0.2.30 
particle-dev-local-compiler 0.1.3 
particle-dev-profiles 0.2.3 
particle-dev-release-notes 0.53.2 
particle-offline-compiler 0.1.3 
tool-bar 1.1.4 
```

**Comment by fabripeco** [comment]
Restarting Atom works for me on Ubuntu 17.10, selecting the .ino file of the correct project, in project tab...
